name: Run tests for the capture groups
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Run-tests-on-Ubuntu:
    name: Run tests for hdl/asm dirs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: install tree-sitter-cli
        run: |
          npm install -g tree-sitter-cli
          tree-sitter --version
      - name: run hdl tests
        run: |
          cd /home/runner/work/tree-sitter-nand2tetris/tree-sitter-nand2tetris
          cd tree-sitter-hackhdl
          tree-sitter generate
          tree-sitter test
      - name: run asm tests
        run: |
          cd /home/runner/work/tree-sitter-nand2tetris/tree-sitter-nand2tetris
          cd tree-sitter-hackasm
          tree-sitter generate
          tree-sitter test
          
          
