name: Run tests for the capture groups
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Run-tests-on-Ubuntu:
    name: Run tests for hdl/asm dirs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: run npm
        run: |
          cd /home/runner/work/tree-sitter-nand2tetris/tree-sitter-nand2tetris
          cd tree-sitter-hackhdl
          pwd
          npm install
          cd node_modules
          ls -a
          cd tree-sitter-cli
          ls -a
          ./node_modules/tree-sitter-cli/tree-sitter -h
